version: "3"

services:
  app:
    build: .
    container_name: "rpc-app_v1.0"
    environment:
      - RPC_ADDR=:9001
      - HTTP_ADDR=:8001
      - PG_PORT=5432
    tty: true
    restart: on-failure
    ports:
      - "9001:9000"
      - "8001:8000"
    depends_on:
      - postgres-db
    networks:
      - back
    volumes:
      - .:/app

  postgres-db:
    image: postgres:latest
    container_name: "rpc-app-db_v1.0"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres-db
    networks:
      - back

networks:
  back:
    driver: bridge
